import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "@/lib/query-provider";
import Navbar from "@/components/Navbar/navbar";
import { Toaster } from "@/components/ui/sonner";
import ManifestProgress from "@/components/ManifestProgress";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Guardians",
  description: "Generated by a Destiny 2 Fan, for Destiny 2 Fans",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <ManifestProgress />
          <Navbar />
          {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
